### ISSUE TITLE
linuxserver/tautulli:2.12.4 not starting

### ISSUE THREAD

**Issue by shadowempire123** [Tautulli/Tautulli-Remote#209]
### Describe the bug

2.12.4 on portainer is not working.
2.12.3 no problem

see logs
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Tautulli: https://tautulli.com/#donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[custom-init] No custom files found, skipping...
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'

### Expected Behavior

Ubuntu 22.04.2 LTS 

### Tautulli Remote Version

2.12.4

### Tautulli Version

2.12.4

### Mobile Device

dfd

### Mobile OS

dfdf

**Comment by TheMeanCanEHdian** [comment]
This is not related to the Tautulli Remote mobile app

**Comment by shadowempire123** [comment]
who else to ask...?

**Comment by samwiseg0** [comment]
@shadowempire123 Please use the discord server for support. https://tautulli.com/discord.html
