### ISSUE TITLE
App crashes on Cast when tapping on information (i) icon

### ISSUE THREAD

**Issue by reguerap** [Tautulli/Tautulli-Remote#74]
Actual behaviour: app crashes when tapping on information icon (i) for a current activity entry when a video is casting to a chromecast device

Expected behaviour: information to display on screen.

Steps to reproduce: 
1. open plex app and connect to chromecast device.
2. Start casting a video
3. Open tautulli remote
4. Go to menu - activity
5. Tap on the information icon (i) for the casting streaming video.
6. App crashes without logs

Impact: Low. Only chromecast affected (so far)

**Comment by Brando47** [comment]
Having the same issue, app crashes immediately when pressing the info button. Thanks for pointing out this is for cast streams, makes a lot more sense

**Comment by jwindelborg** [comment]
I just discovered that the app crashes when the play status is "Error" (as opposed to "Playing" or "Paused"). I assume it's the same problem.

**Comment by jwindelborg** [comment]
After some setup I got a stacktrace for when the app crashes, I will continue and see if I can fix the error, but I am not an android developer so the chances is not too high.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.williamcomartin.plexpyremote, PID: 1377
    java.lang.NumberFormatException: For input string: ""
        at java.lang.Integer.parseInt(Integer.java:627)
        at java.lang.Integer.valueOf(Integer.java:801)
        at com.williamcomartin.plexpyremote.Models.ActivityModels$Activity.get_bandwidth_string(ActivityModels.java:304)
        at com.williamcomartin.plexpyremote.databinding.FragmentStreamInfoBinding.executeBindings(FragmentStreamInfoBinding.java:236)
        at android.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:381)
        at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:353)
        at android.databinding.ViewDataBinding$6.run(ViewDataBinding.java:178)
        at android.databinding.ViewDataBinding$7.doFrame(ViewDataBinding.java:251)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1310)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1123)
        at android.view.Choreographer.doFrame(Choreographer.java:934)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1298)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:7029)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by Yrlish** [comment]
This same behavior happens when pressing the info button on a DLNA stream.

**Comment by TheMeanCanEHdian** [comment]
Closing out now that Tautulli Remote 2.0 is released. If you think this is still valid please open a new bug report or feature request:

https://github.com/Tautulli/Tautulli-Remote/issues/new/choose
